import { NextRequest, NextResponse } from 'next/server'
import busboy from 'busboy'
import fs from 'fs/promises'
import { createWriteStream } from 'fs'
import { randomBytes } from 'crypto'
import { Readable, Writable } from 'stream'
import { isImageFile } from '@/lib/utils'
import { prisma } from '@/lib/db'
import { DEFAULT_APP_SETTINGS, mapDbAppSettings } from '@/lib/settings'
import {
  createUploadTempImagePath,
  createUploadTempPaths,
  ensureUploadTempCapacity,
  MAX_DIRECT_UPLOAD_BYTES,
  MAX_UPLOAD_TEMP_BYTES_PER_JOB,
  pruneStaleUploadTempArtifacts,
} from '@/lib/upload-temp'
import {
  ImportSettings,
  ImportSettingsValidationError,
  formatImportSettingsValidationError,
  parseImportSettings,
} from '@/lib/import-settings'

export const dynamic = 'force-dynamic'

type UploadMode = 'zip' | 'files'

type UploadedTempImage = {
  originalName: string
  tmpPath: string
  bytesWritten: number
}

type StreamResult = {
  mode: UploadMode
  rollName: string
  rollId?: string
  settings: ImportSettings
  fileName: string
  bytesWritten: number
  tmpZip: string | null
  imageFiles: UploadedTempImage[]
}

class UploadError extends Error {
  constructor(message: string, public readonly status = 400) {
    super(message)
  }
}

class UploadLimitError extends UploadError {
  constructor(message: string) {
    super(message, 413)
  }
}

function normalizeRollId(value: string): string | undefined {
  const trimmed = value.trim()
  if (!trimmed) return undefined
  // Roll ids are generated by Prisma cuid() and are URL-safe strings.
  if (!/^[a-zA-Z0-9_-]{8,128}$/.test(trimmed)) {
    throw new UploadError('Invalid rollId')
  }
  return trimmed
}

async function removeTempArtifacts(tmpZip: string, imageFiles: UploadedTempImage[] = []) {
  await fs.unlink(tmpZip).catch(() => {})
  await Promise.all(imageFiles.map(file => fs.unlink(file.tmpPath).catch(() => {})))
}

async function getUploadTempTtlMs() {
  const settings = await prisma.appSettings.findUnique({ where: { id: 'singleton' } })
  const hours = settings
    ? mapDbAppSettings(settings).dataSafety.keepUploadTempFilesHours
    : DEFAULT_APP_SETTINGS.dataSafety.keepUploadTempFilesHours

  return hours * 60 * 60 * 1000
}

/** Stream multipart body to temp files on disk while enforcing upload ceilings. */
async function streamToDisk(
  request: NextRequest,
  jobId: string,
  tmpZip: string,
  contentType: string,
): Promise<StreamResult> {
  return new Promise((resolve, reject) => {
    let settled = false
    const done = (fn: () => void) => {
      if (!settled) {
        settled = true
        fn()
      }
    }

    const bb = busboy({ headers: { 'content-type': contentType } })
    const openWriters = new Set<Writable>()
    const abortError = new UploadError('Upload was interrupted before completion. Please try again.', 400)
    let totalRequestBytes = 0

    const destroyWriters = () => {
      for (const ws of openWriters) {
        ws.destroy(abortError)
      }
      openWriters.clear()
    }

    const onAbort = () => {
      destroyWriters()
      bb.destroy(abortError)
    }
    request.signal.addEventListener('abort', onAbort, { once: true })
    let rollName = ''
    let rollId: string | undefined
    const rawSettings: { frameNumberStart?: string; autoRotationPolicy?: string; duplicateHandling?: string } = {}
    let zipName = ''
    let zipBytes = 0
    let zipCount = 0
    let imageCount = 0
    let imageIndex = 0
    const imageFiles: UploadedTempImage[] = []
    const writes: Promise<void>[] = []

    bb.on('file', (_field, stream, info) => {
      const { filename } = info
      if (!filename) {
        stream.resume()
        return
      }

      const lower = filename.toLowerCase()
      if (lower.endsWith('.zip')) {
        if (zipCount > 0 || imageCount > 0) {
          stream.resume()
          done(() => reject(new UploadError('Upload either one .zip or multiple image files, not both.')))
          return
        }

        zipCount += 1
        zipName = filename
        const ws = createWriteStream(tmpZip)
        openWriters.add(ws)
        const writePromise = new Promise<void>((res, rej) => {
          ws.on('finish', () => {
            openWriters.delete(ws)
            res()
          })
          ws.on('error', rej)
          stream.on('error', rej)
        })
        stream.on('data', (chunk: Buffer) => {
          totalRequestBytes += chunk.length
          zipBytes += chunk.length
          if (totalRequestBytes > MAX_DIRECT_UPLOAD_BYTES || zipBytes > MAX_UPLOAD_TEMP_BYTES_PER_JOB) {
            stream.unpipe(ws)
            ws.destroy(new UploadLimitError('Upload exceeds the maximum allowed size.'))
            stream.destroy(new UploadLimitError('Upload exceeds the maximum allowed size.'))
          }
        })
        stream.pipe(ws)
        writes.push(writePromise)
        return
      }

      if (!isImageFile(filename)) {
        stream.resume()
        done(() => reject(new UploadError('Please upload either a .zip file or supported image files.')))
        return
      }

      if (zipCount > 0) {
        stream.resume()
        done(() => reject(new UploadError('Upload either one .zip or multiple image files, not both.')))
        return
      }

      imageCount += 1
      imageIndex += 1
      const tmpPath = createUploadTempImagePath(jobId, imageIndex, filename)
      const ws = createWriteStream(tmpPath)
      openWriters.add(ws)
      let imageBytes = 0
      const writePromise = new Promise<void>((res, rej) => {
        ws.on('finish', () => {
          openWriters.delete(ws)
          res()
        })
        ws.on('error', rej)
        stream.on('error', rej)
      })
      stream.on('data', (chunk: Buffer) => {
        totalRequestBytes += chunk.length
        imageBytes += chunk.length
        if (totalRequestBytes > MAX_DIRECT_UPLOAD_BYTES) {
          stream.unpipe(ws)
          ws.destroy(new UploadLimitError('Upload exceeds the maximum allowed size.'))
          stream.destroy(new UploadLimitError('Upload exceeds the maximum allowed size.'))
        }
      })
      stream.pipe(ws)
      writes.push(writePromise)
      imageFiles.push({ originalName: filename, tmpPath, bytesWritten: 0 })
      writePromise.then(() => {
        const target = imageFiles.find(file => file.tmpPath === tmpPath)
        if (target) {
          target.bytesWritten = imageBytes
        }
      }).catch(() => {})
    })

    bb.on('field', (name, val) => {
      if (name === 'name') rollName = val.trim()
      if (name === 'rollId') {
        rollId = normalizeRollId(val)
      }
      if (name === 'frameNumberStart') rawSettings.frameNumberStart = val.trim()
      if (name === 'autoRotationPolicy') rawSettings.autoRotationPolicy = val.trim()
      if (name === 'duplicateHandling') rawSettings.duplicateHandling = val.trim()
    })

    bb.on('finish', async () => {
      try {
        await Promise.all(writes)
        const settings = parseImportSettings(rawSettings)

        if (zipCount === 1) {
          done(() => resolve({
            mode: 'zip',
            rollName,
            rollId,
            settings,
            fileName: zipName,
            bytesWritten: zipBytes,
            tmpZip,
            imageFiles: [],
          }))
          return
        }

        if (imageCount > 0) {
          done(() => resolve({
            mode: 'files',
            rollName,
            rollId,
            settings,
            fileName: imageCount === 1 ? imageFiles[0].originalName : `${imageCount} files`,
            bytesWritten: imageFiles.reduce((sum, file) => sum + file.bytesWritten, 0),
            tmpZip: null,
            imageFiles,
          }))
          return
        }

        done(() => reject(new UploadError('No files provided')))
      } catch (err) {
        done(() => reject(err))
      }
    })

    bb.on('close', () => {
      request.signal.removeEventListener('abort', onAbort)
    })
    bb.on('error', (err) => {
      destroyWriters()
      done(() => reject(err))
    })

    const bodyStream = Readable.fromWeb(request.body as any)
    bodyStream.on('error', (err) => {
      destroyWriters()
      bb.destroy(err instanceof Error ? err : new Error(String(err)))
    })
    bodyStream.on('end', () => {
      request.signal.removeEventListener('abort', onAbort)
    })
    bodyStream.pipe(bb)
  })
}

export async function POST(request: NextRequest) {
  const contentType = request.headers.get('content-type') ?? ''
  if (!contentType.includes('multipart/form-data')) {
    return NextResponse.json({ error: 'Expected multipart/form-data' }, { status: 400 })
  }
  if (!request.body) {
    return NextResponse.json({ error: 'No request body' }, { status: 400 })
  }
  const contentLength = Number(request.headers.get('content-length') ?? '0')
  if (Number.isFinite(contentLength) && contentLength > MAX_DIRECT_UPLOAD_BYTES) {
    return NextResponse.json({ error: 'Upload exceeds the maximum allowed size.' }, { status: 413 })
  }

  try {
    const cleanup = await pruneStaleUploadTempArtifacts(Date.now(), await getUploadTempTtlMs())
    if (cleanup.deleted.length > 0) {
      console.info(
        '[upload] pruned stale temp artifacts',
        JSON.stringify({ scanned: cleanup.scanned, deleted: cleanup.deleted.length, ttlMs: cleanup.ttlMs }),
      )
    }
  } catch (err) {
    console.warn('[upload] temp artifact pruning failed', err)
  }

  try {
    await ensureUploadTempCapacity()
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Upload temp storage is unavailable.'
    return NextResponse.json({ error: message }, { status: 503 })
  }

  const jobId = randomBytes(16).toString('hex')
  const { tmpZip, metaFile } = createUploadTempPaths(jobId)

  try {
    const result = await streamToDisk(request, jobId, tmpZip, contentType)

    // Write job metadata so the processing endpoint can find it
    await fs.writeFile(metaFile, JSON.stringify({
      mode: result.mode,
      tmpZip: result.tmpZip,
      imageFiles: result.imageFiles,
      rollName: result.rollName,
      rollId: result.rollId,
      settings: result.settings,
      fileName: result.fileName,
    }))

    console.info(
      '[upload] created temp upload artifacts',
      JSON.stringify({
        jobId,
        mode: result.mode,
        tmpZip: result.tmpZip,
        imageFiles: result.imageFiles.map(file => ({ tmpPath: file.tmpPath, originalName: file.originalName, bytesWritten: file.bytesWritten })),
        metaFile,
        fileName: result.fileName,
        bytesWritten: result.bytesWritten,
      }),
    )

    return NextResponse.json({ jobId })
  } catch (err) {
    await removeTempArtifacts(tmpZip)
    await fs.unlink(metaFile).catch(() => {})
    if (err instanceof ImportSettingsValidationError) {
      return NextResponse.json(formatImportSettingsValidationError(err), { status: 400 })
    }
    const rawMessage = err instanceof Error ? err.message : 'Upload failed'
    const isUnexpectedEnd = /unexpected end of form/i.test(rawMessage)
    const message = isUnexpectedEnd
      ? 'Upload was interrupted before completion. Please retry and keep this tab open until it finishes.'
      : rawMessage
    const status = err instanceof UploadError ? err.status : 500
    console.error('[upload] failed to ingest upload', JSON.stringify({
      jobId,
      status,
      message,
      rawMessage,
      contentType,
      contentLength: request.headers.get('content-length'),
      aborted: request.signal.aborted,
    }))
    return NextResponse.json({ error: message }, { status })
  }
}
