import { NextRequest, NextResponse } from 'next/server'
import path from 'path'
import fs from 'fs/promises'
import { tmpdir } from 'os'

export const dynamic = 'force-dynamic'

/**
 * POST /api/upload/chunk
 *
 * Receives one raw binary chunk of a file upload.
 * Metadata is carried in request headers so the body can be pure binary
 * (no multipart parsing needed — avoids all busboy/ReadableStream issues).
 *
 * Headers:
 *   x-job-id        — 32-char hex string, generated by the client
 *   x-chunk-index   — 0-based index of this chunk
 *   x-total-chunks  — total number of chunks for this job
 *   x-file-name     — original filename (must end in .zip)
 *   x-roll-name     — optional roll name (URI-encoded)
 */
export async function POST(request: NextRequest) {
  const jobId = request.headers.get('x-job-id') ?? ''
  const chunkIndex = parseInt(request.headers.get('x-chunk-index') ?? '', 10)
  const totalChunks = parseInt(request.headers.get('x-total-chunks') ?? '', 10)
  const fileName = request.headers.get('x-file-name') ?? ''
  const rollName = decodeURIComponent(request.headers.get('x-roll-name') ?? '')

  if (!/^[0-9a-f]{32}$/.test(jobId)) {
    return NextResponse.json({ error: 'Invalid job ID' }, { status: 400 })
  }
  if (!Number.isFinite(chunkIndex) || chunkIndex < 0) {
    return NextResponse.json({ error: 'Invalid x-chunk-index' }, { status: 400 })
  }
  if (!Number.isFinite(totalChunks) || totalChunks <= 0) {
    return NextResponse.json({ error: 'Invalid x-total-chunks' }, { status: 400 })
  }
  if (!fileName.toLowerCase().endsWith('.zip')) {
    return NextResponse.json({ error: 'File must be a .zip' }, { status: 400 })
  }

  try {
    const chunkDir = path.join(tmpdir(), `grained-chunks-${jobId}`)
    await fs.mkdir(chunkDir, { recursive: true })

    // Persist metadata once (on the first chunk)
    if (chunkIndex === 0) {
      await fs.writeFile(
        path.join(chunkDir, 'meta.json'),
        JSON.stringify({ fileName, rollName, totalChunks }),
      )
    }

    // Read the raw binary body — 10 MB chunks are fine in memory
    const data = await request.arrayBuffer()
    if (data.byteLength === 0) {
      return NextResponse.json({ error: 'Empty chunk body' }, { status: 400 })
    }

    const chunkFile = path.join(chunkDir, `chunk-${String(chunkIndex).padStart(6, '0')}`)
    await fs.writeFile(chunkFile, Buffer.from(data))

    return NextResponse.json({ ok: true, chunkIndex })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to save chunk'
    console.error(`[upload/chunk] error saving chunk ${chunkIndex} for job ${jobId}:`, err)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
